/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Kernel launch infrastructure with rust-analyzer type hint support.
//!
//! This module provides traits and helpers for launching CUDA kernels with
//! full IDE type checking. The key insight is separating concerns:
//!
//! - **Macro** (`cuda_launch!`): Captures kernel identifier → PTX name string,
//!   marshals arguments into a `Vec<*mut c_void>`, and calls
//!   `cuda_core::launch_kernel` directly.
//! - **Traits** (`CudaKernel`, `GenericCudaKernel`): Provide PTX entry-point
//!   names for rust-analyzer and compile-time validation.

use std::ffi::c_void;
#[cfg(feature = "async")]
use std::sync::Arc;

// =============================================================================
// Core Traits
// =============================================================================

/// Trait implemented by kernel functions.
///
/// This trait is automatically generated by the `#[kernel]` attribute macro.
/// It provides the PTX entry point name for runtime kernel lookup.
///
/// # Example
///
/// When you write:
/// ```ignore
/// #[kernel]
/// pub fn vecadd(a: &[f32], b: &[f32], mut c: DisjointSlice<f32>) { ... }
/// ```
///
/// The macro generates (on host side only):
/// ```ignore
/// pub struct __vecadd_CudaKernel;
/// impl CudaKernel for __vecadd_CudaKernel {
///     const PTX_NAME: &'static str = "vecadd";  // Original function name
/// }
/// ```
///
/// Note: the function is renamed internally to `cuda_oxide_kernel_<hash>_vecadd`
/// for detection by the compiler backend (the prefix is owned by the
/// workspace-internal `reserved-oxide-symbols` crate), but the PTX entry point
/// uses the original name.
pub trait CudaKernel {
    /// The PTX entry point name (e.g., "vecadd" - the original function name)
    const PTX_NAME: &'static str;
}

/// Trait for generic kernel functions.
///
/// Unlike `CudaKernel`, this trait provides a function to get the PTX name
/// because generic kernels have different PTX names for each type instantiation.
///
/// # Example
///
/// For a generic kernel:
/// ```ignore
/// #[kernel]
/// pub fn scale<T: Copy + Mul<Output = T>>(factor: T, input: &[T], mut out: DisjointSlice<T>) { ... }
/// ```
///
/// The macro generates:
/// ```ignore
/// pub struct __scale_CudaKernel<T>(std::marker::PhantomData<T>);
///
/// impl<T: Copy + Mul<Output = T>> GenericCudaKernel for __scale_CudaKernel<T> {
///     fn ptx_name() -> &'static str {
///         // Hash-based name that matches what the backend generates
///         // e.g., "scale_a1b2c3d4" for scale::<f32>
///     }
/// }
/// ```
///
/// # PTX Naming Scheme
///
/// Non-closure generic kernels use `std::any::type_name::<Self>()` to generate
/// a stable, unique PTX name for each instantiation. Generic closure kernels
/// use [`typed_kernel_ptx_name`] so all closure launch APIs agree with the
/// backend's type-identity export name.
pub trait GenericCudaKernel {
    /// Get the PTX entry point name for this specific instantiation.
    ///
    /// Unlike `CudaKernel::PTX_NAME`, this is a function because the name
    /// depends on the type parameters.
    fn ptx_name() -> &'static str;
}

/// Returns the typed PTX entry name for a generic closure kernel.
///
/// Closure launches use rustc's `TypeId` fingerprint for the tuple of generic
/// arguments, so typed modules and lower-level launch macros agree on one PTX
/// entry name for the same closure instantiation. The cuda backend computes the
/// same fingerprint with `TyCtxt::type_id_hash`.
#[inline]
#[doc(hidden)]
pub fn typed_kernel_ptx_name<GenericArgs>(base: &str) -> &'static str {
    let type_id = type_id_u128::<GenericArgs>();
    Box::leak(format!("{base}__typed_{type_id:032x}").into_boxed_str())
}

#[inline]
fn type_id_u128<T>() -> u128 {
    // cuda-oxide is tied to the rustc that builds the backend. The `type_id`
    // intrinsic is const-evaluated by rustc as `TyCtxt::type_id_hash(ty)`, which
    // is the same value used by the cuda backend's PTX export naming. Keep this
    // in a `const` block: rustc backends do not implement this intrinsic at
    // runtime. Use the intrinsic directly instead of `TypeId::of` because the
    // public API adds a `'static` bound while the intrinsic itself does not.
    let type_id = const { core::intrinsics::type_id::<T>() };
    unsafe { std::mem::transmute::<std::any::TypeId, u128>(type_id) }
}

// =============================================================================
// Typed Kernel Arguments
// =============================================================================

/// Marker trait for values that may be passed to a CUDA kernel by value.
///
/// `#[cuda_module]` uses this trait for scalar kernel parameters. Any `Copy`
/// value can be used here because cuda-oxide compiles the host and device
/// instantiations from the same Rust type. Prefer `#[repr(C)]` for structs that
/// must also interoperate with CUDA C/C++ code.
pub trait KernelScalar: Copy {}

impl<T: Copy> KernelScalar for T {}

/// Pushes a by-value scalar kernel argument into a CUDA driver argument list.
///
/// The pointed-to value must remain alive until the launch submission call has
/// returned. The generated `#[cuda_module]` launch methods create stack locals
/// for this purpose before calling this helper.
#[inline]
#[doc(hidden)]
pub fn push_kernel_scalar<T: KernelScalar>(args: &mut Vec<*mut c_void>, value: &mut T) {
    args.push(value as *mut T as *mut c_void);
}

/// Returns the `(device pointer, element count)` pair used for read-only slice
/// parameters such as `&[T]`.
#[inline]
#[doc(hidden)]
pub fn read_only_device_buffer_arg<T>(
    buffer: &cuda_core::DeviceBuffer<T>,
) -> (cuda_core::sys::CUdeviceptr, u64) {
    (buffer.cu_deviceptr(), buffer.len() as u64)
}

/// Returns the `(device pointer, element count)` pair used for writable slice
/// parameters such as `&mut [T]` and `DisjointSlice<T>`.
#[inline]
#[doc(hidden)]
pub fn writable_device_buffer_arg<T>(
    buffer: &mut cuda_core::DeviceBuffer<T>,
) -> (cuda_core::sys::CUdeviceptr, u64) {
    (buffer.cu_deviceptr(), buffer.len() as u64)
}

/// Pushes a device slice argument pair into a CUDA driver argument list.
///
/// cuda-oxide device slices lower to two kernel parameters: `CUdeviceptr` and
/// `u64` element count. Keeping that encoding here makes the generated
/// `#[cuda_module]` methods target a stable helper instead of open-coding the
/// ABI in every expansion.
#[inline]
#[doc(hidden)]
pub fn push_kernel_device_slice(
    args: &mut Vec<*mut c_void>,
    ptr: &mut cuda_core::sys::CUdeviceptr,
    len: &mut u64,
) {
    args.push(ptr as *mut cuda_core::sys::CUdeviceptr as *mut c_void);
    args.push(len as *mut u64 as *mut c_void);
}

// =============================================================================
// Typed Async Kernel Arguments
// =============================================================================

/// A typed device allocation that can be passed to an async kernel launch as a
/// read-only device slice.
#[cfg(feature = "async")]
pub trait KernelSliceArg {
    /// Element type stored in the allocation.
    type Elem;

    /// Returns the raw CUDA device pointer for the allocation.
    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr;

    /// Returns the number of `T` elements in the allocation.
    fn len(&self) -> usize;

    /// Returns true when the allocation has zero elements.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// A typed device allocation that can be passed to an async kernel launch as a
/// writable device slice.
#[cfg(feature = "async")]
pub trait KernelSliceArgMut: KernelSliceArg {}

#[cfg(feature = "async")]
impl<T> KernelSliceArg for cuda_core::DeviceBuffer<T> {
    type Elem = T;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.len()
    }
}

#[cfg(feature = "async")]
impl<T> KernelSliceArgMut for cuda_core::DeviceBuffer<T> {}

#[cfg(feature = "async")]
impl<T: Send> KernelSliceArg for cuda_async::device_box::DeviceBox<[T]> {
    type Elem = T;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.len()
    }
}

#[cfg(feature = "async")]
impl<T: Send> KernelSliceArgMut for cuda_async::device_box::DeviceBox<[T]> {}

#[cfg(feature = "async")]
impl<B> KernelSliceArg for Arc<B>
where
    B: KernelSliceArg + ?Sized,
{
    type Elem = B::Elem;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.as_ref().cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.as_ref().len()
    }
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn new_async_kernel_launch<'a>(
    func: cuda_core::CudaFunction,
    config: cuda_core::LaunchConfig,
) -> cuda_async::launch::AsyncKernelLaunch<'a> {
    let mut launch = cuda_async::launch::AsyncKernelLaunch::new(Arc::new(func));
    launch.set_launch_config(config);
    launch
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn new_owned_async_kernel_launch<R: Send>(
    launch: cuda_async::launch::AsyncKernelLaunch<'static>,
    resources: R,
) -> cuda_async::launch::OwnedAsyncKernelLaunch<R> {
    cuda_async::launch::OwnedAsyncKernelLaunch::new(launch, resources)
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn set_async_kernel_cluster_dim(
    launch: &mut cuda_async::launch::AsyncKernelLaunch<'_>,
    cluster_dim: (u32, u32, u32),
) {
    launch.set_cluster_dim(cluster_dim);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_kernel_scalar<'a, T: KernelScalar + 'a>(
    launch: &mut cuda_async::launch::AsyncKernelLaunch<'a>,
    value: T,
) {
    launch.push_scalar_arg(value);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_read_only_device_slice<B>(
    launch: &mut cuda_async::launch::AsyncKernelLaunch<'_>,
    buffer: &B,
) where
    B: KernelSliceArg + ?Sized,
{
    launch.push_scalar_arg(buffer.cu_deviceptr());
    launch.push_scalar_arg(buffer.len() as u64);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_writable_device_slice<B>(
    launch: &mut cuda_async::launch::AsyncKernelLaunch<'_>,
    buffer: &mut B,
) where
    B: KernelSliceArgMut + ?Sized,
{
    launch.push_scalar_arg(buffer.cu_deviceptr());
    launch.push_scalar_arg(buffer.len() as u64);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn load_cuda_module_from_async_context<F, R>(
    device_id: usize,
    f: F,
) -> Result<R, cuda_async::error::DeviceError>
where
    F: FnOnce(&Arc<cuda_core::CudaContext>) -> Result<R, cuda_core::EmbeddedModuleError>,
{
    cuda_async::device_context::with_cuda_context(device_id, |ctx| f(ctx))?.map_err(|error| {
        if let cuda_core::EmbeddedModuleError::Driver(error) = error {
            cuda_async::error::DeviceError::Driver(error)
        } else {
            cuda_async::error::DeviceError::KernelCache(error.to_string())
        }
    })
}

/// Async-context counterpart of [`crate::load_kernel_module`].
///
/// Loads a kernel module by stem name on `device_id`, using the async device
/// context map to find the underlying [`cuda_core::CudaContext`].
#[cfg(feature = "async")]
pub fn load_kernel_module_async(
    name: &str,
    device_id: usize,
) -> Result<Arc<cuda_core::CudaModule>, cuda_async::error::DeviceError> {
    cuda_async::device_context::with_cuda_context(device_id, |ctx| {
        crate::ltoir::load_kernel_module(ctx, name)
            .map_err(|error| cuda_async::error::DeviceError::KernelCache(error.to_string()))
    })?
}

// =============================================================================
// Argument Wrapper Types
// =============================================================================

/// Wrapper for scalar values that need to be passed to kernels.
///
/// This wrapper exists for documentation purposes and to make the intent clear.
/// The macro handles unwrapping these properly.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: scale,
///     // ...
///     args: (Scalar(factor), &input_dev, &mut output_dev)
/// }
/// ```
pub struct Scalar<T>(pub T);

/// Wrapper indicating a device buffer is read-only in the kernel.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: transform,
///     // ...
///     args: (ReadOnly(&input_dev), &mut output_dev)
/// }
/// ```
pub struct ReadOnly<'a, T>(pub &'a T);

/// Wrapper indicating a device buffer is write-only in the kernel.
///
/// This is a hint for future optimizations - currently treated same as mutable.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: generate,
///     // ...
///     args: (WriteOnly(&mut output_dev),)
/// }
/// ```
pub struct WriteOnly<'a, T>(pub &'a mut T);

// =============================================================================
// Length Extraction (for slice kernels)
// =============================================================================

/// Trait for types that have a length (used to pass ptr+len to kernels).
pub trait HasLength {
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<T> HasLength for cuda_core::DeviceBuffer<T> {
    fn len(&self) -> usize {
        self.len()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::c_void;

    // Dummy kernel marker for testing
    struct TestKernelMarker;
    impl CudaKernel for TestKernelMarker {
        const PTX_NAME: &'static str = "test_kernel"; // Original function name
    }

    #[repr(C)]
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct TestParams {
        scale: f32,
        bias: i32,
    }

    fn assert_kernel_scalar<T: KernelScalar>() {}

    #[test]
    fn test_ptx_name_lookup() {
        assert_eq!(TestKernelMarker::PTX_NAME, "test_kernel");
    }

    #[test]
    fn test_scalar_wrapper() {
        let s = Scalar(42i32);
        assert_eq!(s.0, 42);
    }

    #[test]
    fn test_kernel_scalar_accepts_copy_argument_kinds() {
        assert_kernel_scalar::<f32>();
        assert_kernel_scalar::<TestParams>();
        assert_kernel_scalar::<*const f32>();
        assert_kernel_scalar::<*mut f32>();

        let offset = 7u32;
        let copy_closure = move |x: u32| x + offset;
        fn assert_value_is_kernel_scalar<T: KernelScalar>(_value: T) {}
        assert_value_is_kernel_scalar(copy_closure);
    }

    #[test]
    fn test_push_kernel_scalar_records_argument_address() {
        let mut args = Vec::new();
        let mut params = TestParams {
            scale: 1.5,
            bias: -2,
        };
        let expected = &mut params as *mut TestParams as *mut c_void;

        push_kernel_scalar(&mut args, &mut params);

        assert_eq!(args, vec![expected]);
        assert_eq!(unsafe { *(args[0] as *const TestParams) }, params);
    }

    #[test]
    fn test_push_kernel_scalar_accepts_copy_closure() {
        let mut args = Vec::new();
        let offset = 3u32;
        let mut copy_closure = move |x: u32| x + offset;
        let expected = &mut copy_closure as *mut _ as *mut c_void;

        push_kernel_scalar(&mut args, &mut copy_closure);

        assert_eq!(args, vec![expected]);
    }

    #[test]
    fn test_push_kernel_scalar_accepts_raw_pointer() {
        let mut args = Vec::new();
        let value = 42f32;
        let mut ptr = &value as *const f32;

        push_kernel_scalar(&mut args, &mut ptr);

        assert_eq!(args.len(), 1);
        assert_eq!(unsafe { *(args[0] as *const *const f32) }, ptr);
    }

    #[test]
    fn test_push_kernel_device_slice_records_pointer_and_len() {
        let mut args = Vec::new();
        let mut ptr: cuda_core::sys::CUdeviceptr = 0xfeed_beefu64;
        let mut len = 1024u64;

        push_kernel_device_slice(&mut args, &mut ptr, &mut len);

        assert_eq!(args.len(), 2);
        assert_eq!(
            unsafe { *(args[0] as *const cuda_core::sys::CUdeviceptr) },
            ptr
        );
        assert_eq!(unsafe { *(args[1] as *const u64) }, len);
    }
}
